// <auto-generated />
using System;
using CRUDUsingEFCoreCodeFirstApproach.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDUsingEFCoreCodeFirstApproach.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20250721083927_AddedProductTable")]
    partial class AddedProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUDUsingEFCoreCodeFirstApproach.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics",
                            Rating = 4
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mobiles",
                            Rating = 5
                        });
                });

            modelBuilder.Entity("CRUDUsingEFCoreCodeFirstApproach.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("ProductName");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("categoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("categoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CRUDUsingEFCoreCodeFirstApproach.Models.Entities.Product", b =>
                {
                    b.HasOne("CRUDUsingEFCoreCodeFirstApproach.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
